/**
 * One-off: turns the traced Verdansk references (kept outside the repo) into game data.
 *   REF=<dir with verdansk.json, sat.rgba, atlas_Full_BG.rgba> TRACE=<dir with roadmask2.bin, cls.bin> node scripts/export-map.mjs
 * World frame: satellite pixels x 3 m. 1080 x 1080 px -> 3240 m square, north = -z... we use z = south.
 */
import fs from 'node:fs';
import zlib from 'node:zlib';
const REF = process.env.REF, TRACE = process.env.TRACE;
const PX = 3, N = 1080, SW = 1075;
const j = JSON.parse(fs.readFileSync(REF + '/verdansk.json', 'utf8'));
const toSat = ([x, y]) => [(x + 0.02788) / 0.0009839, (y + 0.03887) / 0.0009903];
const W = (p) => { const [sx, sy] = toSat(p); return [Math.round(sx * PX), Math.round(sy * PX)]; };
const R = (r) => Math.round((r / 0.00099) * PX);
const pois = j.pois.map((p) => ({ id: p.id, name: p.name, tier: p.tier, x: W([p.x, p.y])[0], z: W([p.x, p.y])[1], r: R(p.radius) }));
const out = {
  size: N * PX,
  pois,
  coast: j.coastline.points.map(W),
  land: j.land_polygon.map(W),
  playable: j.playable_boundary.map(W),
  rivers: j.rivers.map((r) => ({ name: r.name, width: Math.round(R(r.width)), pts: r.points.map(W) })),
  lakes: j.lakes.map((l) => ({ name: l.name, poly: l.polygon.map(W) })),
  roads: j.roads.map((r) => ({ name: r.name, type: r.type, pts: r.points.map(W) })),
  rail: j.rail.map((r) => ({ name: r.name, pts: r.points.map(W) })),
  heights: j.terrain.control_points.map((c) => { const [x, z] = W([c.x, c.y]); return [x, z, c.height_m]; }),
};
const ts = `// Generated by scripts/export-map.mjs from traced 2020 Verdansk references. World metres; x east, z south.\n` +
  `export const VERDANSK = ${JSON.stringify(out)} as const;\n`;
fs.writeFileSync('src/data/verdansk.ts', ts);
// masks
const road = fs.readFileSync(TRACE + '/roadmask2.bin');
const cls = fs.readFileSync(TRACE + '/cls.bin');
const bg = fs.readFileSync(REF + '/atlas_Full_BG.rgba');
const sat = fs.readFileSync(REF + '/sat.rgba');
const m = new Uint8Array(N * N);
for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
  const sx = Math.min(SW - 1, x), si = y * SW + sx;
  let v = 0;
  if (road[si]) v |= 1;
  // building-ish from tac map (bright gray, not road), warped into satellite frame
  const tx = Math.round((sx + 6.7) / 1.023), ty = Math.round((y - 26.4) / 1.012);
  if (tx >= 0 && ty >= 0 && tx < 1080 && ty < 1080) {
    const ti = (ty * 1080 + tx) * 4, r = bg[ti], g = bg[ti + 1], b = bg[ti + 2];
    if (Math.abs(r - g) < 14 && Math.abs(g - b) < 14 && g > 104 && !road[si]) v |= 2;
  }
  if (cls[si] === 4) v |= 4; // bright neutral: snow in the north
  const r = sat[si * 4], g = sat[si * 4 + 1], b = sat[si * 4 + 2];
  if (Math.max(r, g, b) < 30 && y > 800) v |= 8; // sea
  m[y * N + x] = v;
}
fs.writeFileSync('public/map/masks.bin', zlib.deflateSync(m, { level: 9 }));
console.log('pois', pois.length, 'mask bytes', fs.statSync('public/map/masks.bin').size);
